language: ruby
before_script:
  - psql -c 'create database "bundler-api";' -U postgres
  - cp .env.example .env && export $(cat .env) && ./script/setup -v
rvm: 1.9.3
script: export $(cat .env) && rspec
notifications:
  irc:
    on_success: change
    on_failure: always
    channels: "irc.freenode.org#bundler"
  campfire:
    on_success: always
    on_failure: always
    rooms:
      - secure: "B4ev1d4ZH0Xro49xIunvZNAF2LR0hDgvfpzYMcqUlLNtY5YSmUHbyroVU60w\n10pgYkEhH3DXzHGSYLoYlxGC7foFCZhTkf9JaNgIoSnQmFet+7C66wEkskoY\nwa9n1V3WGic5ZFVBnrZ1IFM6D3hLlAfQdwnwC5GWSrSS9B0jjdI="
